mat1<-matrix(1:6,nrow = 2, ncol = 3) 
mat2<-matrix(7:12,nrow = 2, ncol = 3) 
cat("matrix 1") 
print(mat1) 
cat("matrix 2") 
print(mat2) 
combined_col<-cbind(mat1,mat2) 
cat("combined column here")  
print(combined_col) 
combined_row<-rbind(mat1,mat2) 
cat("combined row here") 
print(combined_row) 
